#!/bin/bash

cd $HOME
mkdir .commands
cd .commands
wget https://raw.githubusercontent.com/ZaydTheCoder/pi-ware-1/main/pi-ware-commands
cp ~/.bashrc ~/.commands

echo "source ~/.commands/pi-ware-commands" >> ~/.bashrc

echo "Please restart terminal to apply changes."
echo "
Commands added: 'pi-ware-install', 'pi-ware-uninstall', 'pi-ware-update', 'pi-ware-apps', 'pi-ware-backup'.
'pi-ware-install' installs the program,
'pi-ware-uninstall' uninstalls the program and
'pi-ware-update' updates pi-ware. (Usually not required unless a force update has to be done. Automatic updates will update pi-ware.)
'pi-ware-apps' shows the current app available on pi-ware.
'pi-ware-backup' is NOT to be used unless a developer at pi-ware approves to use it. If this command is used when not required, this could result in a core part of your OS getting damaged and making your OS partially unusable.
Thanks for using pi-ware."
