#!/bin/bash

pi-ware-install():
  git clone https://github.com/zachthecoder14/pi-ware.git
  cd pi-ware
  bash install

pi-ware-uninstall():
  bash ~/pi-ware/uninstall

pi-ware-update():
  bash ~/pi-ware/updater

pi-ware-apps():
  bash ~/pi-ware/.current-apps

pi-ware-backup():
  rm ~/.bashrc
  cp ~/pi-ware/.bashrc ~/.bashrc